osx_image: xcode9
language: objective-c

cache:
  directories:
  - Carthage

before_install:
- travis_wait 35; bin/bootstrap-if-needed

script:
- xcodebuild clean build -project Malibu.xcodeproj -scheme "Malibu-Mac" -sdk macosx
- xcodebuild test -project Malibu.xcodeproj -scheme "Malibu-Mac" -sdk macosx
- xcodebuild clean build -project Malibu.xcodeproj -scheme "Malibu-iOS" -sdk iphonesimulator
- xcodebuild test -project Malibu.xcodeproj -scheme "Malibu-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty

notifications:
  email: false

after_success:
- bash <(curl -s https://codecov.io/bash)
